import type { DnaConfig } from "./types";

export const businessDnaEn: DnaConfig = {
  locale: "en",
  toolTitle: "Build Your Business DNA",
  toolSubtitle:
    "12 quick questions so Chameleon Eye AI knows how to work with your business from day one.",
  hrefs: {
    freeToolsHub: "/free-tools",
    contact: "/contact",
    freeToolsBase: "/free-tools",
  },
  ui: {
    progressTemplate: "Question {n} of {total}",
    nextLabel: "Next",
    backLabel: "Back",
    seeResultLabel: "Build My Business DNA",
    disclaimer:
      "Demo only. Production will save your Business DNA securely in your Chameleon Eye account.",
    resultReadyHeading: "Your Chameleon Business DNA is ready.",
    roleLabel: "Role",
    mainFocusLabel: "Main Focus",
    preferredStyleLabel: "Preferred Style",
    privacyModeLabel: "Privacy Mode",
    recommendedStartLabel: "Recommended Start",
    tagsHeading: "Intelligence Tags",
    aiInstructionHeading: "AI Instruction Summary",
    startScanCta: "Start First Scan",
    tryToolsCta: "Try Free Tools",
    requestDemoCta: "Request Demo",
    editDnaCta: "Edit Business DNA",
  },
  focusMap: {
    cash_waste: { label: "Cash Waste", reportLabel: "Cash Waste Report", toolSlug: "cash-waste-scanner" },
    team_inefficiency: {
      label: "Team Effectiveness",
      reportLabel: "Team Effectiveness Report",
      toolSlug: "team-effectiveness-check",
    },
    customer_journey: {
      label: "Customer Journey",
      reportLabel: "Customer Journey Report",
      toolSlug: "customer-journey-friction-test",
    },
    risk_watch: {
      label: "Operational Risk",
      reportLabel: "Risk & Private Mode Report",
      toolSlug: "private-mode-readiness-test",
    },
  },
  tagLabels: {
    founder: "Founder",
    manager: "Manager",
    consultant: "Consultant",
    operations_lead: "Operations Lead",
    saas_marketplace: "SaaS / Marketplace",
    retail_ecommerce: "Retail / E-commerce",
    professional_services: "Professional Services",
    traditional_business: "Traditional Business",
    cash_waste: "Cash Waste",
    team_inefficiency: "Team Inefficiency",
    customer_journey: "Customer Journey",
    risk_watch: "Risk Watch",
    fast_decisive: "Fast Decisive",
    data_driven: "Data-Driven",
    cautious: "Cautious",
    collaborative: "Collaborative",
    executive_summary: "Executive Summary",
    detailed_report: "Detailed Report",
    quick_score: "Quick Score",
    action_plan: "Action Plan",
    local_private_mode: "Local Private Mode",
    hybrid_mode: "Hybrid Mode",
    cloud_first: "Cloud First",
  },
  questions: [
    {
      id: "role",
      text: "What's your role?",
      options: [
        { label: "Business Owner / Founder", tags: ["founder"] },
        { label: "Manager / Executive", tags: ["manager"] },
        { label: "Consultant / Advisor", tags: ["consultant"] },
        { label: "Operations / Team Lead", tags: ["operations_lead"] },
      ],
    },
    {
      id: "businessType",
      text: "What type of business do you run?",
      options: [
        { label: "SaaS / Marketplace", tags: ["saas_marketplace"] },
        { label: "Retail / E-commerce", tags: ["retail_ecommerce"] },
        { label: "Professional Services", tags: ["professional_services"] },
        { label: "Traditional / Other Business", tags: ["traditional_business"] },
      ],
    },
    {
      id: "mainGoal",
      text: "What's your main goal right now?",
      options: [
        { label: "Grow faster", tags: ["growth"] },
        { label: "Cut costs and waste", tags: ["cash_waste"] },
        { label: "Reduce operational risk", tags: ["risk_watch"] },
        { label: "Prepare for investment or exit", tags: ["fundraising_readiness"] },
      ],
    },
    {
      id: "biggestWorry",
      text: "What worries you most about the business today?",
      options: [
        { label: "Hidden cash waste", tags: ["cash_waste"] },
        { label: "Team inefficiency", tags: ["team_inefficiency"] },
        { label: "Customer churn or lost sales", tags: ["customer_journey"] },
        { label: "Compliance or operational risk", tags: ["risk_watch"] },
      ],
    },
    {
      id: "decisionStyle",
      text: "How do you usually make decisions?",
      options: [
        { label: "Fast and decisive", tags: ["fast_decisive"] },
        { label: "Data-driven and careful", tags: ["data_driven"] },
        { label: "Cautious and risk-averse", tags: ["cautious"] },
        { label: "Collaborative, with the team", tags: ["collaborative"] },
      ],
    },
    {
      id: "preferredOutput",
      text: "What kind of output do you prefer from a report?",
      options: [
        { label: "Executive summary with action plan", tags: ["executive_summary", "action_plan"] },
        { label: "Detailed report with full data", tags: ["detailed_report"] },
        { label: "Quick score only", tags: ["quick_score"] },
        { label: "Full step-by-step action plan", tags: ["action_plan"] },
      ],
    },
    {
      id: "tone",
      text: "What communication tone works best for you?",
      options: [
        { label: "Direct and concise", tags: ["direct"] },
        { label: "Formal and structured", tags: ["formal"] },
        { label: "Friendly and conversational", tags: ["friendly"] },
        { label: "Technical and precise", tags: ["technical"] },
      ],
    },
    {
      id: "hiddenCost",
      text: "Where do you suspect hidden costs are coming from?",
      options: [
        { label: "Marketing spend", tags: ["marketing_waste"] },
        { label: "Operational waste", tags: ["operational_waste"] },
        { label: "Staff time", tags: ["staff_time_waste"] },
        { label: "Not sure yet", tags: [] },
      ],
    },
    {
      id: "earlyWarning",
      text: "What should Chameleon Eye AI watch for as an early warning?",
      options: [
        { label: "Cash waste alerts", tags: ["cash_waste"] },
        { label: "Risk or compliance alerts", tags: ["risk_watch"] },
        { label: "Customer journey drop-offs", tags: ["customer_journey"] },
        { label: "Team effectiveness signals", tags: ["team_inefficiency"] },
      ],
    },
    {
      id: "dataType",
      text: "What type of data will you mostly work with?",
      options: [
        { label: "Financial data", tags: ["financial_data"] },
        { label: "Customer data", tags: ["customer_data"] },
        { label: "Operational data", tags: ["operational_data"] },
        { label: "HR / team data", tags: ["hr_data"] },
      ],
    },
    {
      id: "sensitivity",
      text: "How sensitive is that data?",
      options: [
        { label: "Highly confidential", tags: ["highly_sensitive"] },
        { label: "Moderately sensitive", tags: ["moderately_sensitive"] },
        { label: "Low sensitivity", tags: ["low_sensitivity"] },
        { label: "Mixed sensitivity", tags: ["mixed_sensitivity"] },
      ],
    },
    {
      id: "privacyMode",
      text: "How should Chameleon Eye AI handle your data by default?",
      options: [
        { label: "Local first, cloud only with approval", tags: ["local_private_mode"] },
        { label: "Hybrid — I choose each time", tags: ["hybrid_mode"] },
        { label: "Cloud first, convenience matters most", tags: ["cloud_first"] },
        { label: "Not sure yet, default to the safest option", tags: ["local_private_mode"] },
      ],
    },
  ],
};

export const businessDnaAr: DnaConfig = {
  locale: "ar",
  toolTitle: "أنشئ Business DNA الخاص بك",
  toolSubtitle:
    "12 سؤالاً سريعاً حتى يعرف Chameleon Eye AI كيف يعمل مع شركتك منذ اليوم الأول.",
  hrefs: {
    freeToolsHub: "/ar/free-tools",
    contact: "/ar/contact",
    freeToolsBase: "/ar/free-tools",
  },
  ui: {
    progressTemplate: "السؤال {n} من {total}",
    nextLabel: "التالي",
    backLabel: "السابق",
    seeResultLabel: "أنشئ Business DNA الخاص بي",
    disclaimer:
      "هذا عرض تجريبي فقط. في الإصدار النهائي سيتم حفظ Business DNA بأمان داخل حسابك في Chameleon Eye.",
    resultReadyHeading: "Business DNA الخاص بك في Chameleon Eye جاهز الآن.",
    roleLabel: "الدور",
    mainFocusLabel: "التركيز الرئيسي",
    preferredStyleLabel: "الأسلوب المفضل",
    privacyModeLabel: "وضع الخصوصية",
    recommendedStartLabel: "البداية الموصى بها",
    tagsHeading: "وسوم الذكاء",
    aiInstructionHeading: "ملخص تعليمات AI",
    startScanCta: "ابدأ أول فحص",
    tryToolsCta: "جرّب الأدوات المجانية",
    requestDemoCta: "اطلب عرضاً توضيحياً",
    editDnaCta: "تعديل Business DNA",
  },
  focusMap: {
    cash_waste: { label: "الهدر المالي", reportLabel: "تقرير الهدر المالي", toolSlug: "cash-waste-scanner" },
    team_inefficiency: {
      label: "فعالية الفريق",
      reportLabel: "تقرير فعالية الفريق",
      toolSlug: "team-effectiveness-check",
    },
    customer_journey: {
      label: "رحلة العميل",
      reportLabel: "تقرير رحلة العميل",
      toolSlug: "customer-journey-friction-test",
    },
    risk_watch: {
      label: "المخاطر التشغيلية",
      reportLabel: "تقرير المخاطر والوضع الخاص",
      toolSlug: "private-mode-readiness-test",
    },
  },
  tagLabels: {
    founder: "مؤسس",
    manager: "مدير",
    consultant: "مستشار",
    operations_lead: "قائد عمليات",
    saas_marketplace: "SaaS / سوق إلكتروني",
    retail_ecommerce: "تجزئة / تجارة إلكترونية",
    professional_services: "خدمات مهنية",
    traditional_business: "شركة تقليدية",
    cash_waste: "هدر مالي",
    team_inefficiency: "ضعف فعالية الفريق",
    customer_journey: "رحلة العميل",
    risk_watch: "مراقبة المخاطر",
    fast_decisive: "قرارات سريعة",
    data_driven: "قائم على البيانات",
    cautious: "حذر",
    collaborative: "تعاوني",
    executive_summary: "ملخص تنفيذي",
    detailed_report: "تقرير مفصل",
    quick_score: "درجة سريعة",
    action_plan: "خطة عمل",
    local_private_mode: "وضع خاص محلي",
    hybrid_mode: "وضع مختلط",
    cloud_first: "سحابي أولاً",
  },
  questions: [
    {
      id: "role",
      text: "ما هو دورك؟",
      options: [
        { label: "صاحب شركة / مؤسس", tags: ["founder"] },
        { label: "مدير / تنفيذي", tags: ["manager"] },
        { label: "مستشار", tags: ["consultant"] },
        { label: "قائد عمليات / فريق", tags: ["operations_lead"] },
      ],
    },
    {
      id: "businessType",
      text: "ما نوع شركتك؟",
      options: [
        { label: "SaaS / سوق إلكتروني", tags: ["saas_marketplace"] },
        { label: "تجزئة / تجارة إلكترونية", tags: ["retail_ecommerce"] },
        { label: "خدمات مهنية", tags: ["professional_services"] },
        { label: "شركة تقليدية / أخرى", tags: ["traditional_business"] },
      ],
    },
    {
      id: "mainGoal",
      text: "ما هدفك الرئيسي حالياً؟",
      options: [
        { label: "النمو بشكل أسرع", tags: ["growth"] },
        { label: "خفض التكاليف والهدر", tags: ["cash_waste"] },
        { label: "تقليل المخاطر التشغيلية", tags: ["risk_watch"] },
        { label: "الاستعداد للاستثمار أو الخروج", tags: ["fundraising_readiness"] },
      ],
    },
    {
      id: "biggestWorry",
      text: "ما الذي يقلقك أكثر بخصوص شركتك اليوم؟",
      options: [
        { label: "هدر مالي خفي", tags: ["cash_waste"] },
        { label: "ضعف فعالية الفريق", tags: ["team_inefficiency"] },
        { label: "فقدان العملاء أو المبيعات", tags: ["customer_journey"] },
        { label: "مخاطر الامتثال أو التشغيل", tags: ["risk_watch"] },
      ],
    },
    {
      id: "decisionStyle",
      text: "كيف تتخذ قراراتك عادة؟",
      options: [
        { label: "سريعة وحاسمة", tags: ["fast_decisive"] },
        { label: "قائمة على البيانات وحذرة", tags: ["data_driven"] },
        { label: "حذرة ومتجنبة للمخاطر", tags: ["cautious"] },
        { label: "تعاونية مع الفريق", tags: ["collaborative"] },
      ],
    },
    {
      id: "preferredOutput",
      text: "أي نوع من المخرجات تفضله في التقرير؟",
      options: [
        { label: "ملخص تنفيذي مع خطة عمل", tags: ["executive_summary", "action_plan"] },
        { label: "تقرير مفصل ببيانات كاملة", tags: ["detailed_report"] },
        { label: "درجة سريعة فقط", tags: ["quick_score"] },
        { label: "خطة عمل كاملة خطوة بخطوة", tags: ["action_plan"] },
      ],
    },
    {
      id: "tone",
      text: "ما أسلوب التواصل الأنسب لك؟",
      options: [
        { label: "مباشر ومختصر", tags: ["direct"] },
        { label: "رسمي ومنظم", tags: ["formal"] },
        { label: "ودّي وحواري", tags: ["friendly"] },
        { label: "تقني ودقيق", tags: ["technical"] },
      ],
    },
    {
      id: "hiddenCost",
      text: "من أين تشك أن التكاليف الخفية تأتي؟",
      options: [
        { label: "الإنفاق التسويقي", tags: ["marketing_waste"] },
        { label: "الهدر التشغيلي", tags: ["operational_waste"] },
        { label: "وقت الموظفين", tags: ["staff_time_waste"] },
        { label: "غير متأكد بعد", tags: [] },
      ],
    },
    {
      id: "earlyWarning",
      text: "ما الذي يجب أن يراقبه Chameleon Eye AI كإنذار مبكر؟",
      options: [
        { label: "تنبيهات الهدر المالي", tags: ["cash_waste"] },
        { label: "تنبيهات المخاطر أو الامتثال", tags: ["risk_watch"] },
        { label: "نقاط توقف رحلة العميل", tags: ["customer_journey"] },
        { label: "إشارات فعالية الفريق", tags: ["team_inefficiency"] },
      ],
    },
    {
      id: "dataType",
      text: "ما نوع البيانات التي ستتعامل معها في الغالب؟",
      options: [
        { label: "بيانات مالية", tags: ["financial_data"] },
        { label: "بيانات العملاء", tags: ["customer_data"] },
        { label: "بيانات تشغيلية", tags: ["operational_data"] },
        { label: "بيانات موارد بشرية / فريق", tags: ["hr_data"] },
      ],
    },
    {
      id: "sensitivity",
      text: "ما مدى حساسية هذه البيانات؟",
      options: [
        { label: "سرية للغاية", tags: ["highly_sensitive"] },
        { label: "حساسة إلى حد ما", tags: ["moderately_sensitive"] },
        { label: "حساسية منخفضة", tags: ["low_sensitivity"] },
        { label: "حساسية مختلطة", tags: ["mixed_sensitivity"] },
      ],
    },
    {
      id: "privacyMode",
      text: "كيف يجب أن يتعامل Chameleon Eye AI مع بياناتك افتراضياً؟",
      options: [
        { label: "محلي أولاً، السحابة فقط بموافقة", tags: ["local_private_mode"] },
        { label: "مختلط — أختار في كل مرة", tags: ["hybrid_mode"] },
        { label: "سحابي أولاً، الأولوية للراحة", tags: ["cloud_first"] },
        { label: "غير متأكد، استخدم الخيار الأكثر أماناً", tags: ["local_private_mode"] },
      ],
    },
  ],
};
